//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kinect_D2_v1
{
    using System;
    using System.Collections.Generic;
    
    public partial class JointValue
    {
        public long id { get; set; }
        public Nullable<double> xValue { get; set; }
        public Nullable<double> yValue { get; set; }
        public Nullable<double> zValue { get; set; }
    }
}
